dependencies {
    implementation project(":conduit-api")

    testImplementation libs.minestom
    testImplementation libs.adventure.text.minimessage
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
