[versions]
minestom = "2026.10.05-26.2"
adventure = "5.2.0"
junit = "6.0.1"

[libraries]
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }