[versions]
minestom = "2026.10.05-26.2"
adventure = "5.2.0"

[libraries]
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }